// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvDRJPpJyN0_b37_9p4ErnFRqfwgxWoYQ',
    appId: '1:44655120540:web:1d1a3cd3ec322dd6a7dd59',
    messagingSenderId: '44655120540',
    projectId: 'budget-app-379022',
    authDomain: 'budget-app-379022.firebaseapp.com',
    databaseURL: 'https://budget-app-379022-default-rtdb.firebaseio.com',
    storageBucket: 'budget-app-379022.appspot.com',
    measurementId: 'G-W29GBPT2HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINO0Fqi9dzy7iwkaA1cNY5SrO11gltxU',
    appId: '1:44655120540:android:60cc921728653f23a7dd59',
    messagingSenderId: '44655120540',
    projectId: 'budget-app-379022',
    databaseURL: 'https://budget-app-379022-default-rtdb.firebaseio.com',
    storageBucket: 'budget-app-379022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCCUh2e3s_xhYkVnsL4XkT8QCqBA-Xf8E',
    appId: '1:44655120540:ios:656a4f48f2597fc9a7dd59',
    messagingSenderId: '44655120540',
    projectId: 'budget-app-379022',
    databaseURL: 'https://budget-app-379022-default-rtdb.firebaseio.com',
    storageBucket: 'budget-app-379022.appspot.com',
    iosClientId: '44655120540-aseq4om1lvm6274p2h05sm9cnpgisbh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.budget3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCCUh2e3s_xhYkVnsL4XkT8QCqBA-Xf8E',
    appId: '1:44655120540:ios:656a4f48f2597fc9a7dd59',
    messagingSenderId: '44655120540',
    projectId: 'budget-app-379022',
    databaseURL: 'https://budget-app-379022-default-rtdb.firebaseio.com',
    storageBucket: 'budget-app-379022.appspot.com',
    iosClientId: '44655120540-aseq4om1lvm6274p2h05sm9cnpgisbh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.budget3',
  );
}
